name: 'TypeScript Browser: Run WASM unit tests'

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'ffi/ts/src/**'
      - 'ffi/ts/scripts/**'
      - '.github/workflows/ts-browser-unit-tests.yml'
  pull_request:
    paths:
      - 'ffi/ts/src/**'
      - 'ffi/ts/scripts/**'

jobs:
  run-ts-browser-unit-tests:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-15"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.51'
          actions-cache-folder: 'emsdk-cache'

      - name: Verify Emscripten installation
        run: emcc --version

      - name: Install dependencies
        run: |
          cd ffi/ts
          npm install --ignore-scripts

      - name: Build WASM module
        run: |
          cd ffi/ts
          npm run build:wasm

      - name: Build TypeScript (browser)
        run: |
          cd ffi/ts
          npm run build:browser

      - name: Run browser tests
        run: |
          cd ffi/ts
          npm run test:browser
