name: 'TypeScript: Run unit tests'

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  ts-run-unit-tests:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-15"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install system dependencies
        run: |
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get update && sudo apt-get install -y swig autoconf automake libtool pkg-config git python3 build-essential
          elif [[ $RUNNER_OS == 'macOS' ]]; then
            brew install swig autoconf automake libtool pkg-config git
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Build blsct.node
        run: |
          cd ffi/ts
          npm install

      - name: Run tests
        run: |
          cd ffi/ts
          npx jest

